name: CI
on:  
  pull_request:    
    branches:
    - master  
jobs:  
  build:     
   runs-on: ubuntu-latest
   
   steps:    
   - uses: actions/checkout@v2
   - name: install package
     run: |
       python setup.py

   - name: test package
     run: |
       pytest tests
 