name: CI
on:  
  pull_request:    
 
jobs:  
  build:     
   runs-on: ubuntu-latest
   
   steps:    
   - uses: actions/checkout@v2
   - uses: s-weigand/setup-conda@v1

   - name: install cadquery
     run: |
      conda install -c conda-forge -c cadquery cadquery=2

   - name: install package
     run: |
       pip install .

   - name: test package
     run: |
       pip install pytest
       pytest tests
